// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyC1nKVWluxxS3d3uKNez0mBCLCgRRdiay0',
//     appId: '1:422493089123:web:388be2fd6312f7bd6ff756',
//     messagingSenderId: '422493089123',
//     projectId: 'planttagger',
//     authDomain: 'planttagger.firebaseapp.com',
//     storageBucket: 'planttagger.appspot.com',
//     measurementId: 'G-HDG3SDNNJQ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCw1gIOkBcAXfMsvWsOJi3hRfZ4oHP4nEY',
//     appId: '1:422493089123:android:a7aecfcbdcd885f46ff756',
//     messagingSenderId: '422493089123',
//     projectId: 'planttagger',
//     storageBucket: 'planttagger.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA1UixooTcR68h-1U4JnE4Dsh6cQ4PLjbI',
//     appId: '1:422493089123:ios:61d249b3d319a4bb6ff756',
//     messagingSenderId: '422493089123',
//     projectId: 'planttagger',
//     storageBucket: 'planttagger.appspot.com',
//     androidClientId: '422493089123-fgte0dtaslj7bk5ff8fp4bnt7k6u5mud.apps.googleusercontent.com',
//     iosClientId: '422493089123-ntt4hmj7r9j3g8cvah2782kfai3vfmg8.apps.googleusercontent.com',
//     iosBundleId: 'com.sdss.planter',
//   );
// }
